apiVersion: v1
kind: Service
metadata:
  name: hotel-api-service
  labels:
    name: hotel-api-service
spec:
  selector:
    app: hotel-api
    version: v1
  ports:
  - name: http
    port: 80
    protocol: tcp
	  targetPort: 8000